# Generated by Django 2.2 on 2019-05-28 08:35

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContractCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('furigana', models.CharField(max_length=100)),
                ('department_name', models.CharField(max_length=80)),
                ('contract_start_date', models.DateTimeField()),
                ('contract_end_date', models.DateTimeField()),
                ('diagnosis_date', models.DateTimeField()),
                ('is_diagnosis_complete', models.BooleanField(default=False)),
                ('business_type', models.SmallIntegerField()),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dc_contract_companies',
            },
        ),
        migrations.CreateModel(
            name='IrricUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('furigana', models.CharField(max_length=40)),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dc_irric_users',
            },
        ),
        migrations.CreateModel(
            name='ServiceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=40)),
                ('available_users', models.IntegerField()),
                ('available_movies', models.IntegerField()),
                ('valid_start_date', models.DateTimeField()),
                ('valid_end_date', models.DateTimeField()),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dc_service_info',
            },
        ),
        migrations.CreateModel(
            name='SystemInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_unusable_from_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('admin_unusable_to_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_unusable_from_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_unusable_to_date', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dc_system_info',
            },
        ),
        migrations.CreateModel(
            name='SystemModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_dir_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=512)),
                ('model_filename', models.CharField(max_length=512)),
                ('label_filename', models.CharField(max_length=512)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_user', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'dc_system_models',
            },
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_use', models.SmallIntegerField(default=0)),
                ('external_use', models.SmallIntegerField(default=0)),
                ('driving_day', models.DateField(blank=True, default=None, null=True)),
                ('vehicle_number', models.IntegerField(default=0)),
                ('analysis_count', models.IntegerField(default=0)),
                ('is_save', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('vehicle_type', models.SmallIntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('status_message', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('path', models.CharField(max_length=512)),
                ('filename', models.CharField(max_length=512)),
                ('length', models.IntegerField(blank=True, default=None, null=True)),
                ('media_type', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('meta_data', models.TextField(blank=True, default=None, null=True)),
                ('parameter', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('user_model_name', models.CharField(blank=True, default=None, max_length=512, null=True)),
                ('user_parameter_name', models.CharField(blank=True, default=None, max_length=521, null=True)),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contract_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.ContractCompany')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_model', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_admin.SystemModel')),
            ],
            options={
                'db_table': 'dc_user_movies',
            },
        ),
        migrations.CreateModel(
            name='UserMovieStatusLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log', models.TextField(default=None)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.UserMovie')),
            ],
            options={
                'db_table': 'dc_user_movie_status_logs',
            },
        ),
        migrations.CreateModel(
            name='UserMovieResultUnsafeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.UserMovie')),
            ],
            options={
                'db_table': 'dc_user_movie_result_unsafe_data',
            },
        ),
        migrations.CreateModel(
            name='UserMovieProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(blank=True, default=None, null=True)),
                ('created_json_flag', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.UserMovie')),
            ],
            options={
                'db_table': 'dc_user_movie_progress',
            },
        ),
        migrations.CreateModel(
            name='UserContractCompanyRelated',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_type', models.SmallIntegerField()),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contract_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.ContractCompany')),
                ('irric_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.IrricUser')),
            ],
            options={
                'db_table': 'dc_user_contract_company_related',
            },
        ),
        migrations.CreateModel(
            name='ContractCompanyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('furigana', models.CharField(max_length=40)),
                ('gender', models.SmallIntegerField()),
                ('birth_date', models.DateField()),
                ('recruit_date', models.DateField()),
                ('total_mileage', models.SmallIntegerField()),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('contract_company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.ContractCompany')),
            ],
            options={
                'db_table': 'dc_contract_company_users',
            },
        ),
        migrations.AddField(
            model_name='contractcompany',
            name='main_consultant_irric_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.IrricUser'),
        ),
        migrations.AddField(
            model_name='contractcompany',
            name='service_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.ServiceInfo'),
        ),
    ]
