# Generated by Django 2.2 on 2019-06-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractcompanyuser',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
