# Generated by Django 2.2 on 2019-06-11 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0002_contractcompanyuser_age'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserMovieResultUnsafeData',
            new_name='UserMovieAnalysisResult',
        ),
        migrations.AlterModelTable(
            name='usermovieanalysisresult',
            table='dc_user_movie_analysis_results',
        ),
    ]
