# Generated by Django 2.2 on 2019-06-18 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0004_businesstype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractcompany',
            name='business_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_admin.BusinessType'),
        ),
    ]
