# Generated by Django 2.2 on 2019-07-05 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_admin', '0005_auto_20190618_1418'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermovie',
            old_name='path',
            new_name='unique_filename',
        ),
    ]
