# Generated by Django 2.2 on 2019-05-28 08:35

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=256, unique=True)),
                ('email', models.EmailField(blank=True, default=None, max_length=256, null=True)),
                ('is_force_password_change', models.BooleanField(default=False)),
                ('is_delete', models.BooleanField(default=False)),
                ('is_inactive', models.BooleanField(default=False)),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dc_users',
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('group_name', models.CharField(max_length=40)),
                ('admin_functions_class', models.SmallIntegerField()),
                ('created_user_id', models.CharField(max_length=8)),
                ('updated_user_id', models.CharField(max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'dc_user_groups',
            },
        ),
    ]
