# Generated by Django 2.2 on 2019-07-05 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='aiframeinfo',
            index=models.Index(fields=['movie', 'fno', 'speed'], name='ai_frame_in_movie_i_eafe76_idx'),
        ),
        migrations.AddIndex(
            model_name='aiframeobject',
            index=models.Index(fields=['movie', 'fno', 'tag'], name='ai_frame_ob_movie_i_f89136_idx'),
        ),
        migrations.AddIndex(
            model_name='aiframeobject',
            index=models.Index(fields=['movie', 'fno', 'tag', 'score'], name='ai_frame_ob_movie_i_72048c_idx'),
        ),
        migrations.AddIndex(
            model_name='aiframeobject',
            index=models.Index(fields=['movie', 'fno', 'tag', 'score', 'pose_ground_center'], name='ai_frame_ob_movie_i_17e8a1_idx'),
        ),
    ]
