# Generated by Django 2.2 on 2019-07-12 11:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_ai', '0002_auto_20190705_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimovie',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
