version: '3.7'
services:
  django:
    restart: always
    build: ./django
    expose:
      - "8000"
    depends_on:
      - postgres
    command: bash -c "python manage.py createcachetable;\
      python manage.py migrate auth;\
      python manage.py migrate sessions;\
      python manage.py migrate;\
      python manage.py migrate --database ai app_ai;\
      gunicorn config.wsgi -b 0.0.0.0:8000"
    #volumes:
    #  - "staticdata:/opt/static/"
  nginx:
    restart: always
    image: nginx
    depends_on:
      - django
    ports:
      - "80:8080"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "staticdata:/opt/apps/DashCamAnalysisWeb/static/"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    #volumes:
    #  - "dbdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_PASSWORD: postgres

#volumes:
#  dbdata:
#  staticdata:
